//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using IronSchool.Entities;
using IronSchool.Repositories.Interfaces;

namespace IronSchool.Repositories
{
    public partial class RoleRepository : EntityRepositoryBase<Role>, IRoleRepository
    {
    
    }
}
