
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IronSchool.Entities
{

using IronSchool.Entities.Base;
using System;
    using System.Collections.Generic;
    
public partial class Course
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Course()
    {

        this.StudentsInCourse = new HashSet<StudentsInCourse>();

    }


    public long CourseId { get; set; }

    public string Description { get; set; }

    public long InstructorId { get; set; }

    public System.DateTime StartDate { get; set; }

    public System.DateTime FinishDate { get; set; }

    public short StudentCountMax { get; set; }



    public virtual Instructor Instructor { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StudentsInCourse> StudentsInCourse { get; set; }

}

}
