
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IronSchool.Entities
{

using IronSchool.Entities.Base;
using System;
    using System.Collections.Generic;
    
public partial class Instructor
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Instructor()
    {

        this.Course = new HashSet<Course>();

    }


    public long InstructorId { get; set; }

    public System.DateTime BirthDate { get; set; }

    public string Address { get; set; }

    public string ContactPhone { get; set; }

    public string Sex { get; set; }

    public decimal Salary { get; set; }

    public long UserId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Course> Course { get; set; }

    public virtual User User { get; set; }

}

}
