
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IronSchool.Entities
{

using IronSchool.Entities.Base;
using System;
    using System.Collections.Generic;
    
public partial class Rule : IActivableEntity
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Rule()
    {

        this.Role = new HashSet<Role>();

    }


    public long RuleId { get; set; }

    public string RuleDefinition { get; set; }

    public string DisplayName { get; set; }

    public bool Active { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Role> Role { get; set; }

}

}
