
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IronSchool.Entities
{

using IronSchool.Entities.Base;
using System;
    using System.Collections.Generic;
    
public partial class Student
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Student()
    {

        this.StudentsInCourse = new HashSet<StudentsInCourse>();

    }


    public long StudentId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public System.DateTime BirthDate { get; set; }

    public string Address { get; set; }

    public string ContactMail { get; set; }

    public string ContactPhone { get; set; }

    public string Sex { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StudentsInCourse> StudentsInCourse { get; set; }

}

}
