
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IronSchool.Entities
{

using IronSchool.Entities.Base;
using System;
    using System.Collections.Generic;
    
public partial class StudentsInCourse
{

    public long StudentId { get; set; }

    public long CourseId { get; set; }

    public Nullable<short> ExamQualification { get; set; }



    public virtual Course Course { get; set; }

    public virtual Student Student { get; set; }

}

}
