

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IronSchool.Repositories
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using IronSchool.Entities;


public partial class DBEntities : DbContext
{
    public DBEntities()
        : base("name=DBEntities")
    {
        InitializeContext();

        this.Configuration.LazyLoadingEnabled = false;

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Course> Course { get; set; }

    public virtual DbSet<Instructor> Instructor { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<Rule> Rule { get; set; }

    public virtual DbSet<Student> Student { get; set; }

    public virtual DbSet<StudentsInCourse> StudentsInCourse { get; set; }

    public virtual DbSet<User> User { get; set; }

}

}

