//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using IronSchool.Business.Base;
using IronSchool.Entities;
using IronSchool.Repositories.Interfaces;

namespace IronSchool.Business
{
    public partial class CourseBusiness : EntityBusinessBase<Course, ICourseRepository>
    {
    
    }
}
